export const INCREMENT_AMOUNT = 'INCREMENT_AMOUNT';
export const DECREMENT_AMOUNT = 'DECREMENT_AMOUNT';
export const FILL_INITIAL_STATE_ORDER = 'FILL_INITIAL_STATE_ORDER';
export const SELECT_TOPPING = 'SELECT_TOPPING';
export const CLEAN_STATE_ORDER = 'CLEAN_STATE_ORDER';
